### PR TITLE
Tests & CI

### PR DESCRIPTION
**Pull request by deadtrickster**
Moved from https://github.com/cl-plus-ssl/cl-plus-ssl/issues/23

I'm about to propose relatively huge changes, like moving all ffi stuff to separate package.
However I'm not feeling comfortable about this considering the fact I can not test anything. 
What I'm proposing:
- [x] Choose test framework (5AM)
- [x] Choose implemenation manager (CIM)
- [x] Setup Travis CI environment
- [ ] Move old tests to 5am

### CODE REVIEW

**Comment by deadtrickster** [comment]
Could you please turn on Travis-CI integration for this repository?

**Comment by deadtrickster** [comment]
Could you please turn on Travis-CI integration for this repository?

**Comment by avodonosov** [comment]
Very cool, thanks a lot!

**Comment by deadtrickster** [comment]
wait wait, not so fast. let me port all existing tests to 5am first

**Comment by avodonosov** [comment]
The initial integration is cool anyway.

What do you mean "wait"? Don't merge it?

BTW, the first build seem to fail: https://travis-ci.org/cl-plus-ssl/cl-plus-ssl

**Comment by deadtrickster** [comment]
Could you reopen it or something like that? because for example I pushed possible travis fix. Also have you enabled travis build for pull request or only for master?

**Comment by avodonosov** [comment]
Unfortunately I see not way to reopen, lets continue in #29. 

Pull requests are enabled in travis

**Pull request merged**
