### PR TITLE
Restored compatibility to libssl32 and libeay32 under Windows

### PR DESCRIPTION
**Pull request by kaygro**
Hi, this is basically lispniks pullrequest, but with fallback to libssl32.dll and libeay32.dll added as requested here (https://github.com/cl-plus-ssl/cl-plus-ssl/pull/80)

### CODE REVIEW

**Comment by avodonosov** [comment]
@kaygro , thank you for trying to fix that, but you've obviously haven't tested it.

The fix you propose doesn't load libeay32 at all. Also, ssleay32 and libssl32 exist both for 64 and 32 bit Windows, but your fix loads them only on 32 bit Windows.

**Comment by avodonosov** [comment]
@kaygro , I've added the 1.1 DLL names for Windows, please test.

**Comment by kaygro** [comment]
Good catch! I was unaware that libeay32 was an alias for libcrypto and and since the named libeay binding wasn't referred to anywhere in the source, I thought it was irrelevant.

The "bitness (x86/x86-64)" in the feature tests of cffi binding definitions actually refers to to the lisp implementation, not to the windows version.
And indeed, on a 32 bit lisp (installed on 64-bit windows), it tries to load the 32 bit dlls. Here's some evidence:

32bit ccl
´
 wx86cl
Hi,init
Clozure Common Lisp Version 1.11.5/v1.11.5  (WindowsX8632)

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (ql:quickload :cl+ssl)
To load "cl+ssl":
  Load 1 ASDF system:
    cl+ssl
; Loading "cl+ssl"

(:CL+SSL)
? (cffi:list-foreign-libraries)
(#<FOREIGN-LIBRARY LIBCRYPTO "libcrypto-1_1.dll"> #<FOREIGN-LIBRARY LIBSSL "libss
l-1_1.dll">)
?
´

On the same machine, using 64 bit ccl:
`
wx86cl64
Hi,init
Clozure Common Lisp Version 1.11.5/v1.11.5  (WindowsX8664)

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (ql:quickload :cl+ssl)
To load "cl+ssl":
  Load 1 ASDF system:
    cl+ssl
; Loading "cl+ssl"

(:CL+SSL)
? (cffi:list-foreign-libraries)
(#<FOREIGN-LIBRARY LIBSSL "libssl-1_1-x64.dll"> #<FOREIGN-LIBRARY LIBCRYPTO "libcrypto-1_1-x64.dll">)
`

As you cannot load 32bit dlls into 64 bit processes (at least not using loadlibrary), the proposed fix actually does the right thing (except for the libeay32 blunder).

Testing now on 64 bit without 64bit dlls:
`
 wx86cl64
Hi,init
Clozure Common Lisp Version 1.11.5/v1.11.5  (WindowsX8664)

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (ql:quickload :cl+ssl)
To load "cl+ssl":
  Load 1 ASDF system:
    cl+ssl
; Loading "cl+ssl"
> Error: Unable to load any of the alternatives:
>           ("libssl-1_1-x64.dll")
> While executing: CFFI::FL-ERROR, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
`

Your solution in this case:
`
 wx86cl64
Hi,init
Clozure Common Lisp Version 1.11.5/v1.11.5  (WindowsX8664)

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (ql:quickload :cl+ssl)
To load "cl+ssl":
  Load 1 ASDF system:
    cl+ssl
; Loading "cl+ssl"
[package cl+ssl]> Error: Unable to load any of the alternatives:
>           ("libssl-1_1-x64.dll" "libssl32.dll" "ssleay32.dll")
> While executing: CFFI::FL-ERROR, in process listener(1).

> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 >
`
Even after verifying, 32 bit lisp can fallback to libssl32:
`
wx86cl
Hi,init
Clozure Common Lisp Version 1.11.5/v1.11.5  (WindowsX8632)

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (ql:quickload :cl+ssl)
To load "cl+ssl":
  Load 1 ASDF system:
    cl+ssl
; Loading "cl+ssl"

(:CL+SSL)
? (cffi:list-foreign-libraries)
(#<FOREIGN-LIBRARY LIBCRYPTO "libeay32.dll"> #<FOREIGN-LIBRARY LIBSSL "libssl32.dll">)
?
`


So, i guess the difference is just, that yours just tries to load some 32bit dlls in vain. which amounts to the same outcome, sorry for not including evidence earlier.

**Comment by avodonosov** [comment]
@kaygro, I meant 64 bit lisps should try libssl32.dll, ssleay32.dll too, because old openssl builds named 64bit versions of DLLs the same.

**Comment by kaygro** [comment]
Ok, I wasn't aware of t his adversary naming scheme. Thanks for bearing with me and fixing this issue.

**Comment by avodonosov** [comment]
:) that's traditional for Windows, WinAPI dlls like user32.dll, kernel33.dll, gdi32.dll are named so in 64 bit versions of Windows.

**Pull request closed without merging**
