### PR TITLE
Moving old tests to 5am

### PR DESCRIPTION
**Pull request by deadtrickster**
Continue https://github.com/cl-plus-ssl/cl-plus-ssl/pull/29

I'm about to propose relatively huge changes, like moving all ffi stuff to separate package.
However I'm not feeling comfortable about this considering the fact I can not test anything. 
What I'm proposing:
- [x] Choose test framework (5AM)
- [x] Choose implemenation manager (Roswell)
- [x] Setup Travis CI environment
- [ ] Move old tests to 5am

### CODE REVIEW

**Comment by deadtrickster** [comment]
We almost here for sbcl! https://travis-ci.org/cl-plus-ssl/cl-plus-ssl/jobs/95262234
Please enable https://coveralls.io/ for coverage info.

**Comment by avodonosov** [comment]
coveralls.io enabled

**Comment by avodonosov** [comment]
Let me know when it's ready to merge / close

**Comment by deadtrickster** [comment]
Do you know what ssl-very-test.lisp and test.lisp do? Are you using it? For me they look like a mess. Maybe just remove them?

**Comment by avodonosov** [comment]
I don't remember running the tests, but I remember reading them. What they do - ssl-verify-test.lisp appears to test how certificates are verified. The test.lisp seems to create server and client, using various modes (unwrap-stream automatically or by client, or use lisp BIO [non working afaik]) and then tests how ssl streams transfer data and perform various operations like read-char-no-hand.

Why deleting them? Let them stay, they do not create problems to anyone.

**Comment by deadtrickster** [comment]
I'm trying to convert them to proper 5am tests. And it is surprisingly hard. From your description I understand they were testing important guts. ok.Will try refactor one more time

**Comment by avodonosov** [comment]
See yourself. I don't demand to convert them (I actually don't know what further changes you are going to propose to cl+ssl). But as you don't feel safe without tests, you can borrow something. See yourself.

**Comment by deadtrickster** [comment]
Hey,
Lets merge and close this for now. It already adds value. 
I decided to switch to https://github.com/cl-plus-ssl/cl-plus-ssl/pull/8 since I want to sync with upstream first.
I will return to this when hostname validation merged.

**Comment by avodonosov** [comment]
Hi, thanks. It adds value indeed.

**Pull request merged**
