### PR TITLE
Implement stream-fd for ABCL

### PR DESCRIPTION
**Pull request by easye**
This fixes for broken BIO on OpenSSL 1.1.1 ff. which causes ABCL to
segfault.

This hack allows ABCL to get at the underlying file descriptor using
undocumented portions of the JVM that are not guaranteed to be stable.

Tested under openjdk8 and openjdk11.

c.f. <https://github.com/cl-plus-ssl/cl-plus-ssl/issues/72>,
<https://abcl.org/trac/ticket/464>.

### CODE REVIEW

**Comment by easye** [comment]
Supersedes #97

**Comment by avodonosov** [comment]
Hi @easye , thank you for the patch.

It might be better to wrap the stream-fd body into ignore-errors, incase in future versions of Java these fields are absent or if reflection is forbidden (in java modules environment - I suppose we access private java fields using jss:get-java-field?).

If LispBIOs are fixed in the future, then returning nil instead of signaling an error from stream-fd may let the LispBIOs to handle the interactions.

Also, this let formatting is unusual for cl+ssl code, let's have it as
```common-lisp
  (defmethod stream-fd ((stream system::socket-stream))
    ;;; Don't ask...
    (let* ((s0 (#"getWrappedInputStream" (two-way-stream-input-stream stream)))
           (s1 (jss:get-java-field s0 "in" t))
           (s2 (jss:get-java-field s1 "ch" t)))
      (jss:get-java-field s2 "fdVal" t))))
```

**Comment by easye** [comment]
@avodonosov Addressed points in your review; please review again when you have a a chance.

**Comment by metayan** [comment]
This change breaks both CCL and SBCL.
CCL gives:
~~~
Reader error on #<BASIC-FILE-CHARACTER-INPUT-STREAM
 ("/src/scm/lisp/cl-plus-ssl/src/streams.lisp"/5 UTF-8) #x3020021697ED>,
 near position 19991, within "fields (#\"getWrapped":
Undefined character #\" in a #\# dispatch macro.
~~~

**Comment by easye** [comment]
> Neither SBCL nor CCL likes this change.
> CCL gives:
> 
> ```
> Reader error on #<BASIC-FILE-CHARACTER-INPUT-STREAM
>  ("/src/scm/lisp/cl-plus-ssl/src/streams.lisp"/5 UTF-8) #x3020021697ED>,
>  near position 19991, within "fields (#\"getWrapped":
> Undefined character #\" in a #\# dispatch macro.
> ```

Acknowledged.  Fixing.

**Pull request merged**
