### PR TITLE
Windows improvements

### PR DESCRIPTION
**Pull request by lispnik**
Hi, would you consider reviewing these changes that are geared towards better improving the Windows cl+ssl experience?

I added a .gitattributes to set the eol explicitly to LF. A default install of Git for Windows will checkout cl+ssl out as CRLF. Unfortunately, SBCL can't load such files when Return is embedded in format directives. https://bugs.launchpad.net/sbcl/+bug/720517

There were 2 files **already in the repository** with CRLF line endings, so those were renormalized to LF for consistency.

Finally, I downloaded and installed ALL of the slopro Win32OpenSSL installers and installed each one. The 1.1.0 and 1.1.1 installs both provide a libssl and libcrypto (just like like the other platforms), so in this possibly controversial change, I removed support for 1.0.0 on Windows. 1.0.0 uses old libssleay32 etc. DLLs and not libssl and libcrypto like everything else.  I also updated the docs with a Windows section describing how to get started.

I'll attach CCL 32/64-bit and SBCL 64-bit test runs.

### CODE REVIEW

**Comment by lispnik** [comment]
CCL 32-bit

```
> .\CCL\wx86cl.exe
Clozure Common Lisp Version 1.11.5/v1.11.5  (WindowsX8632)

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (ql:quickload "cl+ssl")
To load "cl+ssl":
  Load 1 ASDF system:
    cl+ssl
; Loading "cl+ssl"
.......................
("cl+ssl")
? (cffi:list-foreign-libraries)
(#<FOREIGN-LIBRARY LIBCRYPTO "libcrypto-1_1.dll"> #<FOREIGN-LIBRARY LIBSSL "libssl-1_1.dll">)
? (ql:quickload "cl+ssl.test")
To load "cl+ssl.test":
  Load 1 ASDF system:
    cl+ssl.test
; Loading "cl+ssl.test"
...
("cl+ssl.test")
? (fiveam:run :cl+ssl)

Running test suite CL+SSL
 Running test COMPAT-OPENSSL-VERSION .
 Running test SANITY-CHECK.1 .
 Running test suite CL+SSL.VERIFY-HOSTNAME
  Running test VERIFY-GOOGLE-CERT-UNIVERSAL-STRING .
  Running test VERIFY-GOOGLE-CERT-PRINTABLE-STRING .
  Running test VERIY-HOSTNAME-SUCCESS ..............
  Running test VERIFY-GOOGLE-CERT .
  Running test VERIFY-GOOGLE-CERT-TELETEX-STRING .
  Running test VERIFY-GOOGLE-CERT-WITHOUT-DNS .
  Running test VERIFY-HOSTNAME-FAIL .........
  Running test VERIFY-GOOGLE-CERT-DNS-WILDCARD .
  Running test VERIFY-GOOGLE-CERT-BMP-STRING .
 Running test SANITY-CHECK.2 .
 Running test suite CL+SSL.SNI
 Running test suite CL+SSL.BADSSL-COM
  Running test EXPIRED ...
  Running test SELF-SIGNED .
  Running test WRONG.HOST ...
  Running test UNTRUSTED-ROOT .
(#<IT.BESE.FIVEAM::TEST-PASSED #xEADF19E> #<IT.BESE.FIVEAM::TEST-PASSED #xEADEFB6> #<IT.BESE.FIVEAM::TEST-PASSED #xEAEBD86> #<IT.BESE.FIVEAM::TEST-PASSED #xEAED866> #<IT.BESE.FIVEAM::TEST-PASSED #xEAED57E> #<IT.BESE.FIVEAM::TEST-PASSED #xEAED5AE> #<IT.BESE.FIVEAM::TEST-PASSED #xEAED5DE> #<IT.BESE.FIVEAM::TEST-PASSED #xEAED60E> #<IT.BESE.FIVEAM::TEST-PASSED #xEAED63E> #<IT.BESE.FIVEAM::TEST-PASSED #xEAED66E> #<IT.BESE.FIVEAM::TEST-PASSED #xEAED69E> #<IT.BESE.FIVEAM::TEST-PASSED #xEAED6CE> #<IT.BESE.FIVEAM::TEST-PASSED #xEAED6FE> #<IT.BESE.FIVEAM::TEST-PASSED #xEAED72E> #<IT.BESE.FIVEAM::TEST-PASSED #xEAED75E> #<IT.BESE.FIVEAM::TEST-PASSED #xEAED78E> #<IT.BESE.FIVEAM::TEST-PASSED #xEAED7BE> #<IT.BESE.FIVEAM::TEST-PASSED #xEAED7EE> #<IT.BESE.FIVEAM::TEST-PASSED #xEB05B4E> #<IT.BESE.FIVEAM::TEST-PASSED #xEB1AD0E> #<IT.BESE.FIVEAM::TEST-PASSED #xEB2FFBE> #<IT.BESE.FIVEAM::TEST-PASSED #xEB2E9F6> #<IT.BESE.FIVEAM::TEST-PASSED #xEB2EB8E> #<IT.BESE.FIVEAM::TEST-PASSED #xEB2ECFE> #<IT.BESE.FIVEAM::TEST-PASSED #xEB2EE6E> #<IT.BESE.FIVEAM::TEST-PASSED #xEB2F02E> #<IT.BESE.FIVEAM::TEST-PASSED #xEB2F17E> #<IT.BESE.FIVEAM::TEST-PASSED #xEB2F276> #<IT.BESE.FIVEAM::TEST-PASSED #xEB2F35E> #<IT.BESE.FIVEAM::TEST-PASSED #xEB2F406> #<IT.BESE.FIVEAM::TEST-PASSED #xEB23B96> #<IT.BESE.FIVEAM::TEST-PASSED #xEB38F3E> #<IT.BESE.FIVEAM::TEST-PASSED #xEB383C6> #<IT.BESE.FIVEAM::TEST-PASSED #xEB31A36> #<IT.BESE.FIVEAM::TEST-PASSED #xEB330F6> #<IT.BESE.FIVEAM::TEST-PASSED #xEB34A76> #<IT.BESE.FIVEAM::TEST-PASSED #xEB4F6EE> #<IT.BESE.FIVEAM::TEST-PASSED #xEB4A6BE> #<IT.BESE.FIVEAM::TEST-PASSED #xEB4BD7E> #<IT.BESE.FIVEAM::TEST-PASSED #xEB4D4BE> #<IT.BESE.FIVEAM::TEST-PASSED #xEB4848E>)
?



```

**Comment by lispnik** [comment]
CCL 64-bit

```
> .\CCL\wx86cl64.exe
Clozure Common Lisp Version 1.11.5/v1.11.5  (WindowsX8664)

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (ql:quickload "cl+ssl")
To load "cl+ssl":
  Load 1 ASDF system:
    cl+ssl
; Loading "cl+ssl"

("cl+ssl")
? (cffi:list-foreign-libraries)
(#<FOREIGN-LIBRARY LIBSSL "libssl-1_1-x64.dll"> #<FOREIGN-LIBRARY LIBCRYPTO "libcrypto-1_1-x64.dll">)
? (ql:quickload "cl+ssl.test")
To load "cl+ssl.test":
  Load 1 ASDF system:
    cl+ssl.test
; Loading "cl+ssl.test"
...
("cl+ssl.test")
? (fiveam:run :cl+ssl)

Running test suite CL+SSL
 Running test suite CL+SSL.SNI
 Running test SANITY-CHECK.2 .
 Running test suite CL+SSL.BADSSL-COM
  Running test WRONG.HOST ...
  Running test UNTRUSTED-ROOT .
  Running test EXPIRED ...
  Running test SELF-SIGNED .
 Running test suite CL+SSL.VERIFY-HOSTNAME
  Running test VERIFY-GOOGLE-CERT-DNS-WILDCARD .
  Running test VERIFY-GOOGLE-CERT-WITHOUT-DNS .
  Running test VERIFY-GOOGLE-CERT-PRINTABLE-STRING .
  Running test VERIFY-GOOGLE-CERT-TELETEX-STRING .
  Running test VERIY-HOSTNAME-SUCCESS ..............
  Running test VERIFY-HOSTNAME-FAIL .........
  Running test VERIFY-GOOGLE-CERT-UNIVERSAL-STRING .
  Running test VERIFY-GOOGLE-CERT .
  Running test VERIFY-GOOGLE-CERT-BMP-STRING .
 Running test SANITY-CHECK.1 .
 Running test COMPAT-OPENSSL-VERSION .
(#<IT.BESE.FIVEAM::TEST-PASSED #x210350FE6D> #<IT.BESE.FIVEAM::TEST-PASSED #x210350DD3D> #<IT.BESE.FIVEAM::TEST-PASSED #x210350DDCD> #<IT.BESE.FIVEAM::TEST-PASSED #x210350E02D> #<IT.BESE.FIVEAM::TEST-PASSED #x210350DC1D> #<IT.BESE.FIVEAM::TEST-PASSED #x210350D9DD> #<IT.BESE.FIVEAM::TEST-PASSED #x210350DA6D> #<IT.BESE.FIVEAM::TEST-PASSED #x210350DAFD> #<IT.BESE.FIVEAM::TEST-PASSED #x210350D8BD> #<IT.BESE.FIVEAM::TEST-PASSED #x21035105FD> #<IT.BESE.FIVEAM::TEST-PASSED #x21035104DD> #<IT.BESE.FIVEAM::TEST-PASSED #x2103511C3D> #<IT.BESE.FIVEAM::TEST-PASSED #x2103511B1D> #<IT.BESE.FIVEAM::TEST-PASSED #x210351154D> #<IT.BESE.FIVEAM::TEST-PASSED #x21035115AD> #<IT.BESE.FIVEAM::TEST-PASSED #x210351160D> #<IT.BESE.FIVEAM::TEST-PASSED #x210351166D> #<IT.BESE.FIVEAM::TEST-PASSED #x21035116CD> #<IT.BESE.FIVEAM::TEST-PASSED #x210351172D> #<IT.BESE.FIVEAM::TEST-PASSED #x210351178D> #<IT.BESE.FIVEAM::TEST-PASSED #x21035117ED> #<IT.BESE.FIVEAM::TEST-PASSED #x210351184D> #<IT.BESE.FIVEAM::TEST-PASSED #x21035118AD> #<IT.BESE.FIVEAM::TEST-PASSED #x210351190D> #<IT.BESE.FIVEAM::TEST-PASSED #x210351196D> #<IT.BESE.FIVEAM::TEST-PASSED #x21035119CD> #<IT.BESE.FIVEAM::TEST-PASSED #x2103511A2D> #<IT.BESE.FIVEAM::TEST-PASSED #x210351115D> #<IT.BESE.FIVEAM::TEST-PASSED #x21035111BD> #<IT.BESE.FIVEAM::TEST-PASSED #x210351121D> #<IT.BESE.FIVEAM::TEST-PASSED #x210351127D> #<IT.BESE.FIVEAM::TEST-PASSED #x21035112DD> #<IT.BESE.FIVEAM::TEST-PASSED #x210351133D> #<IT.BESE.FIVEAM::TEST-PASSED #x210351139D> #<IT.BESE.FIVEAM::TEST-PASSED #x21035113FD> #<IT.BESE.FIVEAM::TEST-PASSED #x210351145D> #<IT.BESE.FIVEAM::TEST-PASSED #x2103511FAD> #<IT.BESE.FIVEAM::TEST-PASSED #x210351424D> #<IT.BESE.FIVEAM::TEST-PASSED #x210353817D> #<IT.BESE.FIVEAM::TEST-PASSED #x2103536C0D> #<IT.BESE.FIVEAM::TEST-PASSED #x210353569D>)
?
```

**Comment by lispnik** [comment]
SBCL 64-bit

```
> sbcl
This is SBCL 1.4.14, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.

WARNING: the Windows port is fragile, particularly for multithreaded
code.  Unfortunately, the development team currently lacks the time
and resources this platform demands.
* (ql:quickload "cl+ssl")
To load "cl+ssl":
  Load 1 ASDF system:
    cl+ssl
; Loading "cl+ssl"
..................................................
[package cl+ssl].....................
("cl+ssl")
* (cffi:list-foreign-libraries)
(#<CFFI:FOREIGN-LIBRARY LIBSSL "libssl-1_1-x64.dll">
 #<CFFI:FOREIGN-LIBRARY LIBCRYPTO "libcrypto-1_1-x64.dll">)
* (ql:quickload "cl+ssl.test")
To load "cl+ssl.test":
  Load 1 ASDF system:
    cl+ssl.test
; Loading "cl+ssl.test"
[package cl+ssl.test]..
("cl+ssl.test")
* (fiveam:run :cl+ssl)

Running test suite CL+SSL
 Running test SANITY-CHECK.1 .
 Running test SANITY-CHECK.2 .
 Running test COMPAT-OPENSSL-VERSION .
 Running test suite CL+SSL.SNI
 Running test suite CL+SSL.VERIFY-HOSTNAME
  Running test VERIY-HOSTNAME-SUCCESS ..............
  Running test VERIFY-HOSTNAME-FAIL .........
  Running test VERIFY-GOOGLE-CERT .
  Running test VERIFY-GOOGLE-CERT-DNS-WILDCARD .
  Running test VERIFY-GOOGLE-CERT-WITHOUT-DNS .
  Running test VERIFY-GOOGLE-CERT-PRINTABLE-STRING .
  Running test VERIFY-GOOGLE-CERT-TELETEX-STRING .
  Running test VERIFY-GOOGLE-CERT-BMP-STRING .
  Running test VERIFY-GOOGLE-CERT-UNIVERSAL-STRING .
 Running test suite CL+SSL.BADSSL-COM
  Running test WRONG.HOST ...
  Running test EXPIRED ...
  Running test SELF-SIGNED .
  Running test UNTRUSTED-ROOT .
(#<IT.BESE.FIVEAM::TEST-PASSED {1002F21F03}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F271E3}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F28EC3}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2C3D3}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2C163}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2BF43}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2BCD3}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2BAB3}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2B843}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2B623}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2B3F3}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2B1D3}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2B013}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2AE93}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2ACD3}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2AB53}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2A9E3}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2E873}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2E603}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2E393}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2E163}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2DF23}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2DD33}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2DB63}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2D9A3}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1002F2D7C3}>
 #<IT.BESE.FIVEAM::TEST-PASSED {100366DB53}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1003687EA3}>
 #<IT.BESE.FIVEAM::TEST-PASSED {100369DE83}>
 #<IT.BESE.FIVEAM::TEST-PASSED {10036B3913}>
 #<IT.BESE.FIVEAM::TEST-PASSED {10036C92A3}>
 #<IT.BESE.FIVEAM::TEST-PASSED {10036EE923}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1003714253}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1006862E03}>
 #<IT.BESE.FIVEAM::TEST-PASSED {10067A8993}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1006573123}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1006A34D93}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1006985C83}>
 #<IT.BESE.FIVEAM::TEST-PASSED {10068D79C3}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1006AA8323}>
 #<IT.BESE.FIVEAM::TEST-PASSED {1006B1AC03}>)
*
```

**Comment by avodonosov** [comment]
Hi, thank you for the pull request. Please keep the old versions support.

**Comment by avodonosov** [comment]
@lispnik, I committed fixes for all the issues you mention except for crlf. 

I'm in doubts about crlf - don't like any automatic conversions when checkout happens.

Probably we should just commit .gitattributes with ‘* text=false‘, this will be enough to avoid sbcl breakage.

Speaking of fixing the existing crlf files, more files than you found use crlf, in particular some where I have ucommited changes.

**Comment by avodonosov** [comment]
@lispnik , I've added .gitattributes with * text=false to prevent the automatic CRLF conversion.

**Comment by avodonosov** [comment]
All points addressed, closing. Thank you for the report and reopen / submit new if questions remain.

**Comment by lispnik** [comment]
cool thanks @avodonosov

**Pull request closed without merging**
